### PR TITLE
add simple gui for easy PoI selection

### PR DESCRIPTION
**Pull request by berengma**
added simple gui and command /poi_gui to open it

btw. 

maybe it is better to define local functions not global ones

instead of function poi.jump (blabla)
use local function poi_jump (blabla)

### CODE REVIEW

**Comment by acmgit** [comment]
I love the GUI, good work ;-).

Define the functions local don't work. But to define local poi{} works and the functions are part of this table with the list.

**Comment by berengma** [comment]
local functions do not work with a point "." inbetween names:

function poi.jump(destination)
         [code]
end

is a global function for an api for example.


youcan make it local by using:

local function poi_jump(destination)
             [code]
end

the point "." in between names seems to be reserved for global declaration
that is why

local function poi.jump(destination)
          [code]
end
 
does notwork.

**Comment by acmgit** [comment]
Is it not enough to delcare "local poi{}" to make the table and all functions in it local?
For me, poi.jump is like a class poi and jump the method in c++, in this case, local poi makes the class with all function local, isn't it?

**Comment by berengma** [comment]
You are right. Cool. I did not know that is possible. :)

**Pull request merged**
